
sonar.projectKey=notes-app
sonar.projectName=Notes App (Frontend + Backend)
sonar.host.url=http://localhost:9000
sonar.token=


sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,frontend/src/**/__tests__/**,backend/test/**
sonar.tests=backend/test,frontend/src/**/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
