sonar.projectKey=notes-app
sonar.projectName=Notes App (Frontend + Backend)
sonar.host.url=http://localhost:9000

sonar.sources=frontend/src,backend
sonar.tests=frontend/src,backend
sonar.token=


sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,frontend/src/assets/**,frontend/src/main.jsx

sonar.test.inclusions=frontend/src/**/__tests__/**/*.jsx,frontend/src/**/__tests__/**/*.js,backend/**/*.test.js,backend/**/*.spec.js

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8